### ISSUE TITLE
supporting multiple bots and allow different role identities 

### ISSUE THREAD

**Issue by mithew** [n3d1117/chatgpt-telegram-bot#54]
I suggest supporting multiple bots and allowing the setting of different role identities to facilitate multiple functions for different bots that need to be changed frequently.

**Comment by n3d1117** [comment]
Hey @mithew, I think what you're asking is a little out of the scope of this project. However, it can be achieved using docker-compose:

Assuming you have `bot1.env` defined:
```bash
OPENAI_API_KEY="XXX"
TELEGRAM_BOT_TOKEN="XXX"
ASSISTANT_PROMPT="Custom prompt for bot #1"
```

And  `bot2.env`:
```bash
OPENAI_API_KEY="XXX"
TELEGRAM_BOT_TOKEN="XXX"
ASSISTANT_PROMPT="Custom prompt for bot #2"
```

Then you can define a custom `docker-compose.yml` along the lines of:

```yaml
version: '3'
services:
  chatgpt-telegram-bot-1:
    build:
      context: .
      dockerfile: bot1/Dockerfile
    volumes:
      - ./bot1:/home/appuser/app
      - ./bot1.env:/home/appuser/app/.env
    restart: always

  chatgpt-telegram-bot-2:
    build:
      context: .
      dockerfile: bot2/Dockerfile
    volumes:
      - ./bot2:/home/appuser/app
      - ./bot2.env:/home/appuser/app/.env
    restart: always
```

And start the two bots with `docker-compose up`. Let me know if it helps!
