### ISSUE TITLE
can't open file '/app/bot/main.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Zoldex** [n3d1117/chatgpt-telegram-bot#632]
tried with Docker Hub and ghcr:

My compose:

```
services:
  chatgpt-telegram-bot:
    container_name: chatgpt-telegram-bot
    image: ghcr.io/n3d1117/chatgpt-telegram-bot:latest
    environment:
      # Your OpenAI API key
      - OPENAI_API_KEY=MYKEY
      # Your Telegram bot token obtained using @BotFather
      - TELEGRAM_BOT_TOKEN=MYTOKEN
      # Telegram user ID of admins, or - to assign no admin
      - ADMIN_USER_IDS=MYID
      # Comma separated list of telegram user IDs, or * to allow all
      - ALLOWED_TELEGRAM_USER_IDS=*
    volumes:
      - '/volume1/docker/chatgpt-telegram-bot:/app'
    restart: unless-stopped

```

Result:
`python: can't open file '/app/bot/main.py': [Errno 2] No such file or directory`

What's wrong?
